name: Build and Deploy React App using AWS SSM Send-Command 
on:
  push:
    branches:
      - test-branch
jobs:
  build-job:
    name: Build New Landing Page
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: AWS SSM Send Command
      uses: peterkimzz/aws-ssm-send-command@1.0.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
        aws-region: us-west-1
        instance-ids: ${{ secrets.INSTANCE_ID  }}
        comment: Deploy the test-branch
        working-directory: /var/www/html/cdn.fungeapp.com
        command: |
          sudo rm npm-*.out
          sudo git stash
          sudo git pull origin test-branch
          sudo mv /var/www/html/cdn.fungeapp.com/node_modules/react-scripts/config/webpack.config.js /var/www/html/cdn.fungeapp.com/tmp/.
          sudo rm -rf node_modules
          sudo rm -rf build
          sudo npm install  2>&1 | tee npm-install.out
          sudo mv /var/www/html/cdn.fungeapp.com/tmp/webpack.config.js /var/www/html/cdn.fungeapp.com/node_modules/react-scripts/config/.
          sudo npm i stream-browserify --save
          sudo npm i crypto-browserify --save
          sudo npm i stream-http --save
          sudo npm i https-browserify --save
          sudo npm i os-browserify --save
          sudo npm run build 2>&1 | tee npm-build.out
          sudo nginx -t
          sudo systemctl restart nginx
    - name: Sleep for 100 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '100s'
        command: |
          sudo /var/www/html/cdn.fungeapp.com/s3-sync.sh