name: Build and Deploy React App using AWS SSM Send-Command 
on:
  push:
    branches:
      - main
jobs:
  build-job:
    name: Build React App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: AWS SSM Send Command
      uses: peterkimzz/aws-ssm-send-command@1.0.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
        aws-region: us-west-1
        instance-ids: ${{ secrets.INSTANCE_ID  }}
        comment: Deploy the main branch
        working-directory: /var/www/html/dev.fungeapp.com
        command: |
          sudo rm package-lock.json npm-*.out
          sudo git pull origin main
          sudo rm package-lock.json
          sudo rm -rf node_modules
          sudo rm -rf build
          sudo npm install  2>&1 | tee npm-install.out
          sudo npm run build 2>&1 | tee npm-build.out
          sudo nginx -t
          sudo systemctl restart nginx
